name: luacheck
on:
  push: {branches: ["master"]}
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install and run Luacheck
      run: |
        sudo apt-get install luarocks
        luarocks install --local luacheck
        /home/runner/.luarocks/bin/luacheck . -q --globals "vim" --allow-defined-top
